In [1]:
import numpy as np

import mne

In [2]:

raw = mne.io.read_raw_fif('F:\SEED\SEED_EEG\Preprocessed_EEG\/1_20131027.mat')

Opening raw data file F:\SEED\SEED_EEG\Preprocessed_EEG\/1_20131027.mat...


C:\Users\gjj\AppData\Local\Temp\ipykernel_15816\4173902839.py:1: RuntimeWarning: This filename (F:\SEED\SEED_EEG\Preprocessed_EEG\/1_20131027.mat) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, _meg.fif, _eeg.fif, _ieeg.fif, raw.fif.gz, raw_sss.fif.gz, raw_tsss.fif.gz, _meg.fif.gz, _eeg.fif.gz or _ieeg.fif.gz
  raw = mne.io.read_raw_fif('F:\SEED\SEED_EEG\Preprocessed_EEG\/1_20131027.mat')


ValueError: file 'F:\\SEED\\SEED_EEG\\Preprocessed_EEG\\1_20131027.mat' does not start with a file id tag

In [3]:
import scipy.io as sio
file_path = 'F:\SEED\SEED_EEG\Preprocessed_EEG\/1_20131027.mat'
data = sio.loadmat(file_path) 

np_arr = np.array(data['EEG']['data'])
np_arr=np_arr.reshape(99,64,640)
raw = mne.EpochsArray(np_arr,info)




KeyError: 'EEG'

In [4]:
dat = list(data.items())
np_arr = np.array(dat)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (18, 2) + inhomogeneous part.

In [5]:
from read_file import read_one_file

In [6]:
raw=read_one_file(file_path)

Creating RawArray with float64 data, n_channels=62, n_times=47001
    Range : 0 ... 47000 =      0.000 ...   235.000 secs
Ready.
Creating RawArray with float64 data, n_channels=62, n_times=46601
    Range : 0 ... 46600 =      0.000 ...   233.000 secs
Ready.
Creating RawArray with float64 data, n_channels=62, n_times=41201
    Range : 0 ... 41200 =      0.000 ...   206.000 secs
Ready.
Creating RawArray with float64 data, n_channels=62, n_times=47601
    Range : 0 ... 47600 =      0.000 ...   238.000 secs
Ready.
Creating RawArray with float64 data, n_channels=62, n_times=37001
    Range : 0 ... 37000 =      0.000 ...   185.000 secs
Ready.
Creating RawArray with float64 data, n_channels=62, n_times=39001
    Range : 0 ... 39000 =      0.000 ...   195.000 secs
Ready.
Creating RawArray with float64 data, n_channels=62, n_times=47401
    Range : 0 ... 47400 =      0.000 ...   237.000 secs
Ready.
Creating RawArray with float64 data, n_channels=62, n_times=43201
    Range : 0 ... 43200 =      

In [7]:
raw.info

AttributeError: 'list' object has no attribute 'info'

In [8]:
type(raw)

list

In [9]:
raw.count

<function list.count(value, /)>

In [10]:
raw.info['sfreq']

AttributeError: 'list' object has no attribute 'info'

In [11]:
raw[0]

<RawArray | 62 x 46001 (230.0 s), ~21.8 MB, data loaded>

In [12]:
raw[1]

<RawArray | 62 x 45601 (228.0 s), ~21.6 MB, data loaded>

In [13]:
raw[0][1]

(array([[ 11.26527786,   8.37445259,   3.60608101, ..., -24.31869507,
         -27.74596214, -22.5007534 ]]),
 array([0.00000e+00, 5.00000e-03, 1.00000e-02, ..., 2.29990e+02,
        2.29995e+02, 2.30000e+02]))

In [14]:
raw[0][0]

(array([[ -3.03983688,  -4.17232513,  -7.48038292, ..., -46.10419273,
         -51.05137825, -43.6604023 ]]),
 array([0.00000e+00, 5.00000e-03, 1.00000e-02, ..., 2.29990e+02,
        2.29995e+02, 2.30000e+02]))

In [15]:
dimen = np.array(raw).shape
print(dimen)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 3 dimensions. The detected shape was (15, 62, 2) + inhomogeneous part.

In [16]:
target_shape = (15, 62, 2)

for i in range(len(target_shape)):
    if data_to_assign_shape[i] != target_shape[i]:
        print(f"Dimension {i} is not matching. Target shape: {target_shape[i]}, Data shape: {data_to_assign_shape[i]}")


NameError: name 'data_to_assign_shape' is not defined

In [17]:
target_shape = (15, 62, 2)

for i in range(len(target_shape)):
    if raw[i] != target_shape[i]:
        print(f"Dimension {i} is not matching. Target shape: {target_shape[i]}, Data shape: {data_to_assign_shape[i]}")


NameError: name 'data_to_assign_shape' is not defined

In [18]:
target_shape = (15, 62, 2)

for i in range(len(target_shape)):
    if raw[i] != target_shape[i]:
        print(f"Dimension {i} is not matching. Target shape: {target_shape[i]}, Data shape: {raw[i]}")

Dimension 0 is not matching. Target shape: 15, Data shape: <RawArray | 62 x 46001 (230.0 s), ~21.8 MB, data loaded>
Dimension 1 is not matching. Target shape: 62, Data shape: <RawArray | 62 x 45601 (228.0 s), ~21.6 MB, data loaded>
Dimension 2 is not matching. Target shape: 2, Data shape: <RawArray | 62 x 40201 (201.0 s), ~19.1 MB, data loaded>


In [19]:
raw[0]
raw[1]
raw[2]

<RawArray | 62 x 40201 (201.0 s), ~19.1 MB, data loaded>

In [20]:
raw[4]

<RawArray | 62 x 36001 (180.0 s), ~17.1 MB, data loaded>

In [21]:
raw[15]


IndexError: list index out of range

In [22]:
numpy_array = np.frombuffer(raw, dtype=object)

ValueError: cannot create an OBJECT array from memory buffer

In [23]:
numpy_array = np.frombuffer(data_to_assign, dtype=np.object)

NameError: name 'data_to_assign' is not defined

In [24]:
numpy_array = np.frombuffer(raw, dtype=np.object)

C:\Users\gjj\AppData\Local\Temp\ipykernel_15816\3145398798.py:1: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  numpy_array = np.frombuffer(raw, dtype=np.object)


AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [25]:
numpy_array = np.frombuffer(raw, dtype=object)

ValueError: cannot create an OBJECT array from memory buffer

In [26]:
numpy_array = np.frombuffer(raw, dtype=np.float)

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [27]:
numpy_array = np.frombuffer(raw, dtype=float)

TypeError: a bytes-like object is required, not 'list'

In [28]:
type(raws)


NameError: name 'raws' is not defined

In [29]:
type(raw)

list

In [30]:
def read_one_file1(file_path):
    """
    input:单个.mat文件路径
    output:raw格式数据
    """
    data = sio.loadmat(file_path) # 读取.mat文件
    # 获取keys并转化为list，获取数据所在key
    keys = list(data.keys())[3:] # 第一个key是__header__，第二个key是__version__，第三个key是__globals__,第四个key才是数据
    # print(keys)
    # 获取数据
    raw_list = [] # 用于存储每个.mat文件中的15段数据
    for i in range(len(keys)):
        # 获取数据
        stamp = data[keys[i]] # stamp是一个numpy数组
        # print(stamp.shape)
        # 创建info
        info = mne.create_info(ch_names=ch_names, sfreq=sfreq, ch_types='eeg')
        # 创建raw，取第5秒开始的数据
        raw = mne.io.RawArray(stamp, info).crop(tmin=5) # crop()函数用于截取数据，raw是一个raw格式的数据
        # 添加到raw_list
        #raw_list.append(raw) #  为什么要添加到raw_list？ 不能直接返回raw吗？ 
    return raw

In [31]:
data = read_one_file1(file_path)
data.info

NameError: name 'ch_names' is not defined

In [32]:
ch_names = ['FP1', 'FPz', 'FP2', 'AF3', 'AF4', 'F7', 'F5', 'F3', 'F1',
            'Fz', 'F2', 'F4', 'F6', 'F8', 'FT7', 'FC5', 'FC3', 'FC1',
            'FCz', 'FC2', 'FC4', 'FC6', 'FT8', 'T7', 'C5', 'C3', 'C1',
            'CZ', 'C2', 'C4', 'C6', 'T8', 'TP7', 'CP5', 'CP3', 'CP1',
            'CPz', 'CP2', 'CP4', 'CP6', 'TP8', 'P7', 'P5', 'P3', 'P1',
            'Pz', 'P2', 'P4', 'P6', 'P8', 'PO7', 'PO5', 'PO3', 'POz',
            'PO4', 'PO6', 'PO8', 'CB1', 'O1', 'Oz', 'O2', 'CB2'] # 64个
# 采样频率
sfreq = 200
# 每个.mat文件中的数据label
basic_label = [1, 0, -1, -1, 0, 1, -1, 0, 1, 1, 0, -1, 0, 1, -1] # 15个

In [33]:
data = read_one_file1(file_path)
data.info

Creating RawArray with float64 data, n_channels=62, n_times=47001
    Range : 0 ... 47000 =      0.000 ...   235.000 secs
Ready.
Creating RawArray with float64 data, n_channels=62, n_times=46601
    Range : 0 ... 46600 =      0.000 ...   233.000 secs
Ready.
Creating RawArray with float64 data, n_channels=62, n_times=41201
    Range : 0 ... 41200 =      0.000 ...   206.000 secs
Ready.
Creating RawArray with float64 data, n_channels=62, n_times=47601
    Range : 0 ... 47600 =      0.000 ...   238.000 secs
Ready.
Creating RawArray with float64 data, n_channels=62, n_times=37001
    Range : 0 ... 37000 =      0.000 ...   185.000 secs
Ready.
Creating RawArray with float64 data, n_channels=62, n_times=39001
    Range : 0 ... 39000 =      0.000 ...   195.000 secs
Ready.
Creating RawArray with float64 data, n_channels=62, n_times=47401
    Range : 0 ... 47400 =      0.000 ...   237.000 secs
Ready.
Creating RawArray with float64 data, n_channels=62, n_times=43201
    Range : 0 ... 43200 =      

<Info | 7 non-empty values
 bads: []
 ch_names: FP1, FPz, FP2, AF3, AF4, F7, F5, F3, F1, Fz, F2, F4, F6, F8, ...
 chs: 62 EEG
 custom_ref_applied: False
 highpass: 0.0 Hz
 lowpass: 100.0 Hz
 meas_date: unspecified
 nchan: 62
 projs: []
 sfreq: 200.0 Hz
>

In [34]:
data


<RawArray | 62 x 40201 (201.0 s), ~19.1 MB, data loaded>

In [35]:
print(data)

<RawArray | 62 x 40201 (201.0 s), ~19.1 MB, data loaded>


In [36]:
target_shape = (15, 62, 2)

for i in range(len(target_shape)):
    if raw[i] != target_shape[i]:
        print(f"Dimension {i} is not matching. Target shape: {target_shape[i]}, Data shape: {raw[i]}")

Dimension 0 is not matching. Target shape: 15, Data shape: <RawArray | 62 x 46001 (230.0 s), ~21.8 MB, data loaded>
Dimension 1 is not matching. Target shape: 62, Data shape: <RawArray | 62 x 45601 (228.0 s), ~21.6 MB, data loaded>
Dimension 2 is not matching. Target shape: 2, Data shape: <RawArray | 62 x 40201 (201.0 s), ~19.1 MB, data loaded>


In [37]:
target_shape = (15, 62, 2)

for idx, vector in enumerate(raw):
    if len(vector) != target_shape[idx]:
        print(f"Vector {idx} does not match. Target shape: {target_shape[idx]}, Data shape: {len(vector)}")


Vector 0 does not match. Target shape: 15, Data shape: 46001
Vector 1 does not match. Target shape: 62, Data shape: 45601
Vector 2 does not match. Target shape: 2, Data shape: 40201


IndexError: tuple index out of range

In [38]:
raw.shape()

AttributeError: 'list' object has no attribute 'shape'

In [39]:
raw=read_one_file(file_path)

Creating RawArray with float64 data, n_channels=62, n_times=47001
    Range : 0 ... 47000 =      0.000 ...   235.000 secs
Ready.
Creating RawArray with float64 data, n_channels=62, n_times=46601
    Range : 0 ... 46600 =      0.000 ...   233.000 secs
Ready.
Creating RawArray with float64 data, n_channels=62, n_times=41201
    Range : 0 ... 41200 =      0.000 ...   206.000 secs
Ready.
Creating RawArray with float64 data, n_channels=62, n_times=47601
    Range : 0 ... 47600 =      0.000 ...   238.000 secs
Ready.
Creating RawArray with float64 data, n_channels=62, n_times=37001
    Range : 0 ... 37000 =      0.000 ...   185.000 secs
Ready.
Creating RawArray with float64 data, n_channels=62, n_times=39001
    Range : 0 ... 39000 =      0.000 ...   195.000 secs
Ready.
Creating RawArray with float64 data, n_channels=62, n_times=47401
    Range : 0 ... 47400 =      0.000 ...   237.000 secs
Ready.
Creating RawArray with float64 data, n_channels=62, n_times=43201
    Range : 0 ... 43200 =      

In [40]:
def get_list_dimension(lst):
    if not isinstance(lst, list):
        return 0  # 不是列表，认为是0维
    if not lst:  # 空列表，认为是1维
        return 1
    return 1 + get_list_dimension(lst[0])  # 递归计算维度



In [41]:
get_list_dimension(raw)

1

In [42]:
def get_list_dimension1(lst):
    dim = 0
    while isinstance(lst, list):
        if not lst:  # 空列表，认为是1维
            return 1
        dim += 1
        lst = lst[0]
    return dim

# 举例：
my_list = [1, 2, [3, 4], [5, [6, 7]]]
dimension = get_list_dimension(my_list)
print(f"The list is {dimension} dimensional.")


The list is 1 dimensional.


In [43]:
def get_list_dimension(lst):
    dim = 0
    while isinstance(lst, list):
        if not lst:  # 如果是空列表，认为是1维
            return 1
        dim += 1
        lst = lst[0]
    return dim

# 示例：
my_list = [1, 2, [3, 4], [5, [6, 7]]]
dimension = get_list_dimension(my_list)
print(f"The list is {dimension} dimensional.")


The list is 1 dimensional.


In [44]:
def get_list_dimension(lst):
    if not isinstance(lst, list):
        return 0  # 如果不是列表，认为是0维
    if not lst:  # 如果是空列表，认为是1维
        return 1
    # 递归计算维度
    return 1 + get_list_dimension(lst[1])

# 示例：
my_list = [1, 2, [3, 4], [5, [6, 7]]]
dimension = get_list_dimension(my_list)
print(f"The list is {dimension} dimensional.")

The list is 1 dimensional.


In [45]:
def get_list_dimension(lst):
    if not isinstance(lst, list):
        return 0  # 如果不是列表，认为是0维
    if not lst:  # 如果是空列表，认为是1维
        return 1
    # 递归计算维度
    return 1 + get_list_dimension(lst[1])

# 示例：
my_list = [1, 2, [3, 4], [5, [6, 7]]]
dimension = get_list_dimension(my_list)
print(f"The list is {dimension} dimensional.")

The list is 1 dimensional.


In [46]:
def get_list_dimension(lst):
    if not isinstance(lst, list):
        return 0  # 如果不是列表，认为是0维
    if not lst:  # 如果是空列表，认为是1维
        return 1
    # 获取列表中第一个元素的维度
    inner_dim = get_list_dimension(lst[0])
    # 列表的维度等于第一个元素的维度加1
    return 1 + inner_dim

# 示例：
my_list = [1, 2, [3, 4], [5, [6, 7]]]
dimension = get_list_dimension(my_list)
print(f"The list is {dimension} dimensional.")

The list is 1 dimensional.
